package ca.alina.to_dolist.database.schema;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import ca.alina.to_dolist.database.schema.Task;
import ca.alina.to_dolist.database.schema.Notif;

import ca.alina.to_dolist.database.schema.TaskDao;
import ca.alina.to_dolist.database.schema.NotifDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig taskDaoConfig;
    private final DaoConfig notifDaoConfig;

    private final TaskDao taskDao;
    private final NotifDao notifDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        taskDaoConfig = daoConfigMap.get(TaskDao.class).clone();
        taskDaoConfig.initIdentityScope(type);

        notifDaoConfig = daoConfigMap.get(NotifDao.class).clone();
        notifDaoConfig.initIdentityScope(type);

        taskDao = new TaskDao(taskDaoConfig, this);
        notifDao = new NotifDao(notifDaoConfig, this);

        registerDao(Task.class, taskDao);
        registerDao(Notif.class, notifDao);
    }
    
    public void clear() {
        taskDaoConfig.clearIdentityScope();
        notifDaoConfig.clearIdentityScope();
    }

    public TaskDao getTaskDao() {
        return taskDao;
    }

    public NotifDao getNotifDao() {
        return notifDao;
    }

}
