package ca.alina.to_dolist.database.schema;

import org.greenrobot.greendao.annotation.*;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit.

/**
 * Entity mapped to table "NOTIF".
 */
@Entity
public class Notif {

    @Id
    private Long id;
    private long taskId;

    @Generated
    public Notif() {
    }

    public Notif(Long id) {
        this.id = id;
    }

    @Generated
    public Notif(Long id, long taskId) {
        this.id = id;
        this.taskId = taskId;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public long getTaskId() {
        return taskId;
    }

    public void setTaskId(long taskId) {
        this.taskId = taskId;
    }

}
